
# This file is automatically generated, you probably don't want to edit this

permtestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permtestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            stat = "stat_mean",
            qtile_det = 50,
            replicates = 1000, ...) {

            super$initialize(
                package="bootstrap",
                name="permtest",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..stat <- jmvcore::OptionList$new(
                "stat",
                stat,
                options=list(
                    "stat_mean",
                    "stat_qtile",
                    "stat_sd",
                    "stat_var"),
                default="stat_mean")
            private$..qtile_det <- jmvcore::OptionInteger$new(
                "qtile_det",
                qtile_det,
                min=1,
                max=100,
                default=50)
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=100,
                max=100000000,
                default=1000)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..stat)
            self$.addOption(private$..qtile_det)
            self$.addOption(private$..replicates)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        stat = function() private$..stat$value,
        qtile_det = function() private$..qtile_det$value,
        replicates = function() private$..replicates$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..stat = NA,
        ..qtile_det = NA,
        ..replicates = NA)
)

permtestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permtestResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two Sample Permutation Test")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Two Sample Permutation Test"))}))

permtestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "permtestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "bootstrap",
                name = "permtest",
                version = c(1,0,0),
                options = options,
                results = permtestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Two Sample Permutation Test
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param stat .
#' @param qtile_det .
#' @param replicates .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
permtest <- function(
    data,
    dep,
    group,
    stat = "stat_mean",
    qtile_det = 50,
    replicates = 1000) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("permtest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- permtestOptions$new(
        dep = dep,
        group = group,
        stat = stat,
        qtile_det = qtile_det,
        replicates = replicates)

    analysis <- permtestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

