
# This file is automatically generated, you probably don't want to edit this

twosampleOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twosampleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            stat = "stat_mean",
            comparison = "comp_diff",
            conflevel = 95,
            replicates = 1000,
            plot = TRUE, ...) {

            super$initialize(
                package="bootstrap",
                name="twosample",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..stat <- jmvcore::OptionList$new(
                "stat",
                stat,
                options=list(
                    "stat_mean",
                    "stat_median",
                    "stat_sd",
                    "stat_var"),
                default="stat_mean")
            private$..comparison <- jmvcore::OptionList$new(
                "comparison",
                comparison,
                options=list(
                    "comp_diff",
                    "comp_ratio"),
                default="comp_diff")
            private$..conflevel <- jmvcore::OptionInteger$new(
                "conflevel",
                conflevel,
                min=1,
                max=100,
                default=95)
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                min=100,
                max=100000000,
                default=1000)
            private$..plot <- jmvcore::OptionBool$new(
                "plot",
                plot,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..stat)
            self$.addOption(private$..comparison)
            self$.addOption(private$..conflevel)
            self$.addOption(private$..replicates)
            self$.addOption(private$..plot)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        stat = function() private$..stat$value,
        comparison = function() private$..comparison$value,
        conflevel = function() private$..conflevel$value,
        replicates = function() private$..replicates$value,
        plot = function() private$..plot$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..stat = NA,
        ..comparison = NA,
        ..conflevel = NA,
        ..replicates = NA,
        ..plot = NA)
)

twosampleResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twosampleResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Two Sample Non-parametric Bootstrap")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Two Sample Non-parametric Bootstrap"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Bootstrap Plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

twosampleBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "twosampleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "bootstrap",
                name = "twosample",
                version = c(1,0,0),
                options = options,
                results = twosampleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Two Sample Non-parametric Bootstrap
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param stat .
#' @param comparison .
#' @param conflevel .
#' @param replicates .
#' @param plot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
twosample <- function(
    data,
    dep,
    group,
    stat = "stat_mean",
    comparison = "comp_diff",
    conflevel = 95,
    replicates = 1000,
    plot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("twosample requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- twosampleOptions$new(
        dep = dep,
        group = group,
        stat = stat,
        comparison = comparison,
        conflevel = conflevel,
        replicates = replicates,
        plot = plot)

    analysis <- twosampleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

